[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # 将超时时间设置为 30 秒
  timeout = 30

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 如果你需要设置环境变量，可以在这里添加
[build.environment]
  NODE_VERSION = "18.16"