import type { Metadata } from 'next';
import { Baloo_Thambi_2 } from 'next/font/google';

import { Toaster } from '@/components/ui/toaster';

import './globals.css';

import { ThemeProvider } from './themeProvider';

const font = Baloo_Thambi_2({ weight: ['500'], subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body className={font.className} suppressHydrationWarning>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange
				>
					<Toaster />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
